[[pages]]
name = "PULSE"
icon = ""
is_section = true

[[pages]]
path = "pages/explorer.py"
name = "Explorer"
icon = ":white_medium_small_square:"

[[pages]]
path = "pages/referendum.py"
name = "Referendum"
icon = ":white_medium_small_square:"

[[pages]]
path = "pages/results.py"
name = "Experiments"
icon = ":white_medium_small_square:"
